name = "ConfidenceInterval"
uuid = "a48aac9b-de58-4e38-8efc-3eec9d655cd3"
authors = ["SimonLdx <simon.landrieux@ens-paris-saclay.fr> and contributors"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
